---
kind: pipeline
type: docker
name: Build

trigger:
  branch:
    - master
  event:
    include:
      - push

steps:
- name: Run dotnet
  image: mcr.microsoft.com/dotnet/sdk:5.0-focal
  commands:
    - dotnet build