---
kind: pipeline
type: kubernetes
name: Dev

trigger:
  branch:
    - master
  event:
    include:
      - push

steps:
- name: Build docker image & push to repository
  image: plugins/docker
  settings:
    registry: ghcr.io
    repo: ghcr.io/tipcat-net/tipcat-net-api
    tags:
      - ${DRONE_COMMIT_SHA:0:7}-DEV
      - ${DRONE_COMMIT_BRANCH}
    force_tag: true
    use_cache: true
    username:
      from_secret: GITHUB_LOGIN
    password:
      from_secret: GITHUB_PASSWORD