// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TipCatDotNet.Data;

namespace TipcatDotNet.Migrations
{
    [DbContext(typeof(CustomerDbContext))]
    [Migration("20210720182954_SeededCountriesAdded")]
    partial class SeededCountriesAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("QrPayments.Data.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Zoe"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Медные трубы"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
